Max7312-library: Max7312 Class Reference
Max7312 Class Reference
#include <Max7312.h>
Public Member Functions
Max7312 (unsigned int pinBase=MAX7312_MIN_PINBASE, unsigned char chipAddress=MAX7312_ADDRESS, unsigned char intPin=MAX7312_INTPIN, unsigned char portDirection1=0x00, unsigned char portDirection2=0x00, unsigned char timeoutFlag=0x01)
virtual ~Max7312 ()
void setChipAddress (unsigned char chipAddress)
void setPinBase (unsigned int pinBase)
void init (unsigned char portDirection1, unsigned char portDirection2, unsigned char timeoutFlag=0x01)
unsigned char readPort1 ()
unsigned char readPort2 ()
void writePort1 (unsigned char portData)
void writePort2 (unsigned char portData)
void polarityInversionPort1 (unsigned char portInversion)
void polarityInversionPort2 (unsigned char portInversion)
void configPort1 (unsigned char portDirection)
void configPort2 (unsigned char portDirection)
void configTimeout (unsigned char timeoutFlag)
void readIntFlag ()
virtual bool isLowerPort (int pin)
virtual bool isPortActive (int pin)
virtual bool isPortInput (int pin)
virtual bool readPort (int pin)
virtual int writePort (int pin, bool newState)
virtual int configPort (int pin, bool newMode)
int getPort1Data () const
int getPort2Data () const
int getPort1Mode () const
int getPort2Mode () const
int getChipAddress () const
int getPinBase () const
virtual wiringPiNodeStruct * getNode ()
Private Member Functions
void initDataBuffers ()
Private Attributes
int fd
struct wiringPiNodeStruct * node
unsigned char _int_pin
unsigned char _port1_data
unsigned char _port2_data
unsigned char _port1_mode
unsigned char _port2_mode
unsigned char _chipAddress
unsigned char _pinBase
unsigned char _intPin
Detailed Description
Definition at line 102 of file Max7312.h.
Constructor & Destructor Documentation
Max7312::Max7312 (unsigned int pinBase = MAX7312_MIN_PINBASE, unsigned char chipAddress = MAX7312_ADDRESS, unsigned char intPin = MAX7312_INTPIN, unsigned char portDirection1 = 0x00, unsigned char portDirection2 = 0x00, unsigned char timeoutFlag = 0x01)
constructor were the specific chip address, the port directions and and the timeoutflag can be set
Parameters
pinBase pinBase can be any number you like above 64
chipAddress chip address between 0x20 and 0x5E
intPin pin where the interrupt is connected to
portDirection1 default values of ports 0-7 (1 - input; 0 - output)
portDirection2 default values of ports 8-15 (1 - input; 0 - output)
timeoutFlag 1 enable Bus timeout, 0 disable Bus timeout
Definition at line 91 of file Max7312.cpp.
References init(), setChipAddress(), and setPinBase().
virtual Max7312::~Max7312 () inline virtual
Definition at line 110 of file Max7312.h.
Member Function Documentation
int Max7312::configPort (int pin, bool newMode) virtual
set a single port to Output or Input - function requrired for wiringPi interface
Parameters
pin - port relative to pinBase
newMode - 0 - Output; 1 - Input
Returns
new value of complete port
Definition at line 368 of file Max7312.cpp.
References _port1_mode, _port2_mode, configPort1(), configPort2(), GET_HIGHER_PIN_ID, GET_LOWER_PIN_ID, and isLowerPort().
Referenced by _configPortMax7312().
void Max7312::configPort1 (unsigned char portDirection)
set byte data to lower configuration register
Parameters
portDirection
Definition at line 238 of file Max7312.cpp.
References _port1_mode, CONFIGURATION_PORT_1, and fd.
Referenced by configPort(), and init().
void Max7312::configPort2 (unsigned char portDirection)
set byte data to higher configuration register
Parameters
portDirection
Definition at line 247 of file Max7312.cpp.
References _port2_mode, CONFIGURATION_PORT_2, and fd.
Referenced by configPort(), and init().
void Max7312::configTimeout (unsigned char timeoutFlag)
(de-)activate I2C-timeout register
Parameters
timeoutFlag
Definition at line 256 of file Max7312.cpp.
References fd, and TIMEOUT_REGISTER.
Referenced by init().
int Max7312::getChipAddress () const inline
Definition at line 151 of file Max7312.h.
References _chipAddress.
virtual wiringPiNodeStruct* Max7312::getNode () inline virtual
Definition at line 153 of file Max7312.h.
References node.
int Max7312::getPinBase () const inline
Definition at line 152 of file Max7312.h.
References _pinBase.
int Max7312::getPort1Data () const inline
Definition at line 147 of file Max7312.h.
References _port1_data.
int Max7312::getPort1Mode () const inline
Definition at line 149 of file Max7312.h.
References _port1_mode.
int Max7312::getPort2Data () const inline
Definition at line 148 of file Max7312.h.
References _port2_data.
int Max7312::getPort2Mode () const inline
Definition at line 150 of file Max7312.h.
References _port2_mode.
void Max7312::init (unsigned char portDirection1, unsigned char portDirection2, unsigned char timeoutFlag = 0x01)
initialize the Max7311
Parameters
portDirection1 default values of ports 0-7 (1 - input; 0 - output)
portDirection2 default values of ports 8-15 (1 - input; 0 - output)
timeoutFlag 1 enable Bus timeout, 0 disable Bus timeout
Definition at line 146 of file Max7312.cpp.
References _chipAddress, _configPortMax7312(), _pinBase, _readPortMax7312(), _writePortMax7312(), configPort1(), configPort2(), configTimeout(), fd, initDataBuffers(), MAX7312_NUM_OF_PORTS, node, readPort1(), and readPort2().
Referenced by Max7312().
void Max7312::initDataBuffers () private
set all port data to 0
Definition at line 173 of file Max7312.cpp.
References _port1_data, and _port2_data.
Referenced by init().
bool Max7312::isLowerPort (int pin) virtual
check if the pin belongs to port1 or port2
Parameters
pin - port relative to pinBase
Returns
TRUE - pin belongs to Port1(lower), FALSE - pin belongs to Port2(higher)
Definition at line 298 of file Max7312.cpp.
References GET_LOWER_PIN_ID.
Referenced by configPort(), isPortActive(), isPortInput(), readPort(), and writePort().
bool Max7312::isPortActive (int pin) virtual
checks if the port pin is active
Parameters
pin - port relative to pinBase
Returns
true - port pin is active, false port pin is inactive
Definition at line 272 of file Max7312.cpp.
References _port1_data, _port2_data, GET_HIGHER_PIN_ID, GET_LOWER_PIN_ID, and isLowerPort().
Referenced by readPort().
bool Max7312::isPortInput (int pin) virtual
checks if the port pin is active
Parameters
pin - port relative to pinBase
Returns
- true port pin is input, false port pin is output
Definition at line 285 of file Max7312.cpp.
References _port1_mode, _port2_mode, GET_HIGHER_PIN_ID, GET_LOWER_PIN_ID, and isLowerPort().
Referenced by readPort().
void Max7312::polarityInversionPort1 (unsigned char portInversion)
set byte data to lower PolarityInversionRegister
Parameters
portInversion
Definition at line 222 of file Max7312.cpp.
References fd, and POLARITY_INVERSION_PORT_1.
void Max7312::polarityInversionPort2 (unsigned char portInversion)
set byte data to lower PolarityInversionRegister
Parameters
portInversion
Definition at line 230 of file Max7312.cpp.
References fd, and POLARITY_INVERSION_PORT_2.
void Max7312::readIntFlag ()
checks the interrupt flag and if set reads the new value
Definition at line 263 of file Max7312.cpp.
bool Max7312::readPort (int pin) virtual
read a single port - function required for wiringPi interface
Parameters
pin - port relative to pinBase
Returns
true - port is active, false - port is inactive
Definition at line 312 of file Max7312.cpp.
References _port1_data, _port2_data, fd, INPUT_PORT_1, INPUT_PORT_2, isLowerPort(), isPortActive(), isPortInput(), OUTPUT_PORT_1, and OUTPUT_PORT_2.
Referenced by _readPortMax7312().
unsigned char Max7312::readPort1 ()
read the value of lower byte
Returns
value of port
Definition at line 185 of file Max7312.cpp.
References _port1_data, fd, and INPUT_PORT_1.
Referenced by init().
unsigned char Max7312::readPort2 ()
read the value of higher byte
Returns
value of port
Definition at line 195 of file Max7312.cpp.
References _port2_data, fd, and INPUT_PORT_2.
Referenced by init().
void Max7312::setChipAddress (unsigned char chipAddress)
sets the chip address if it is in the correct range, otherwise it is set to MAX7312_MIN_ADDRESS
Parameters
chipAddress I2C adress
Definition at line 108 of file Max7312.cpp.
References _chipAddress, MAX7312_MAX_ADDRESS, and MAX7312_MIN_ADDRESS.
Referenced by Max7312().
void Max7312::setPinBase (unsigned int pinBase)
sets the pinBase if it is in the correct range, otherwise it is set to MAX7312_MIN_PINBASE
Parameters
pinBase - any number above 64
Definition at line 128 of file Max7312.cpp.
References _pinBase, and MAX7312_MIN_PINBASE.
Referenced by Max7312().
int Max7312::writePort (int pin, bool newState) virtual
write a single port - function required for wiringPi interface
Parameters
pin - port relative to pinBase
newState - value to port should be set to 0 - OFF, 1 - ON
Returns
new value of complete port
Definition at line 342 of file Max7312.cpp.
References _port1_data, _port2_data, GET_HIGHER_PIN_ID, GET_LOWER_PIN_ID, isLowerPort(), writePort1(), and writePort2().
Referenced by _writePortMax7312().
void Max7312::writePort1 (unsigned char portData)
write byte data to lower port
Parameters
portData
Definition at line 205 of file Max7312.cpp.
References _port1_data, fd, and OUTPUT_PORT_1.
Referenced by writePort().
void Max7312::writePort2 (unsigned char portData)
write byte data to higher port
Parameters
portData
Definition at line 214 of file Max7312.cpp.
References _port2_data, fd, and OUTPUT_PORT_2.
Referenced by writePort().
Member Data Documentation
unsigned char Max7312::_chipAddress private
Definition at line 165 of file Max7312.h.
Referenced by getChipAddress(), init(), and setChipAddress().
unsigned char Max7312::_int_pin private
Definition at line 160 of file Max7312.h.
unsigned char Max7312::_intPin private
Definition at line 167 of file Max7312.h.
unsigned char Max7312::_pinBase private
Definition at line 166 of file Max7312.h.
Referenced by getPinBase(), init(), and setPinBase().
unsigned char Max7312::_port1_data private
Definition at line 161 of file Max7312.h.
Referenced by getPort1Data(), initDataBuffers(), isPortActive(), readPort(), readPort1(), writePort(), and writePort1().
unsigned char Max7312::_port1_mode private
Definition at line 163 of file Max7312.h.
Referenced by configPort(), configPort1(), getPort1Mode(), and isPortInput().
unsigned char Max7312::_port2_data private
Definition at line 162 of file Max7312.h.
Referenced by getPort2Data(), initDataBuffers(), isPortActive(), readPort(), readPort2(), writePort(), and writePort2().
unsigned char Max7312::_port2_mode private
Definition at line 164 of file Max7312.h.
Referenced by configPort(), configPort2(), getPort2Mode(), and isPortInput().
int Max7312::fd private
Definition at line 158 of file Max7312.h.
Referenced by configPort1(), configPort2(), configTimeout(), init(), polarityInversionPort1(), polarityInversionPort2(), readPort(), readPort1(), readPort2(), writePort1(), and writePort2().
struct wiringPiNodeStruct* Max7312::node private
Definition at line 159 of file Max7312.h.
Referenced by getNode(), and init().
The documentation for this class was generated from the following files:
Max7312.h
Max7312.cpp