Max7312-library: Max7312.cpp File Reference
Max7312.cpp File Reference
#include <stddef.h>
#include <wiringPi_Mock.h>
#include <wiringPiI2C_Mock.h>
#include "Max7312.h"
#include "helper.h"
Macros
#define GET_LOWER_PIN_ID(pin) (pin - _pinBase)
#define GET_HIGHER_PIN_ID(pin) (GET_LOWER_PIN_ID(pin) - 8)
Functions
int _readPortMax7312 (struct wiringPiNodeStruct *node, int pin)
void _writePortMax7312 (struct wiringPiNodeStruct *node, int pin, int value)
void _configPortMax7312 (struct wiringPiNodeStruct *node, int pin, int mode)
Macro Definition Documentation
#define GET_HIGHER_PIN_ID (pin) (GET_LOWER_PIN_ID(pin) - 8)
get the pin inside a byte from the pin - relative to pinBase
Parameters
pin - pin relative to pinbase
Returns
ID in the byte
Definition at line 20 of file Max7312.cpp.
Referenced by Max7312::configPort(), Max7312::isPortActive(), Max7312::isPortInput(), and Max7312::writePort().
#define GET_LOWER_PIN_ID (pin) (pin - _pinBase)
get the pin inside a byte from the pin - relative to pinBase
Parameters
pin - pin relative to pinbase
Returns
ID in the byte
Definition at line 13 of file Max7312.cpp.
Referenced by Max7312::configPort(), Max7312::isLowerPort(), Max7312::isPortActive(), Max7312::isPortInput(), and Max7312::writePort().
Function Documentation
void _configPortMax7312 (struct wiringPiNodeStruct * node, int pin, int mode)
set a single port to Output or Input - function requrired for wiringPi interface
Parameters
node link to port structure
pin - port relative to pinBase
mode - 0 - Output; 1 - Input
Definition at line 66 of file Max7312.cpp.
References Max7312::configPort().
Referenced by Max7312::init().
int _readPortMax7312 (struct wiringPiNodeStruct * node, int pin)
read a single port - function required for wiringPi interface
Parameters
node link to port structure
pin - port relative to pinBase
Returns
Definition at line 28 of file Max7312.cpp.
References Max7312::readPort().
Referenced by Max7312::init().
void _writePortMax7312 (struct wiringPiNodeStruct * node, int pin, int value)
write a single port - function requrired for wiringPi interface
Parameters
node link to port structure
pin - port relative to pinBase
value - value to port should be set to 0 - OFF, 1 - ON
Definition at line 47 of file Max7312.cpp.
References Max7312::writePort().
Referenced by Max7312::init().